Controllers/StudentController.cs
using DataAccessLayer.Entities;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CipherStudioTest.Controllers
{
    public class StudentController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly FileUploadService _fileUploadService;

        public StudentController(ApplicationDbContext context, FileUploadService fileUploadService)
        {
            _context = context;
            _fileUploadService = fileUploadService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Student student, IFormFile ImageFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    student.ImagePath = await _fileUploadService.UploadFileAsync(ImageFile, "images");
                    _context.Add(student);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Student data has been saved successfully!";
                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
            }
            return View(student);
        }

        public async Task<IActionResult> List(string searchString)
        {
            var students = from s in _context.Students select s;

            if (searchString != null)
            {
                students = students.Where(s => s.Name.Contains(searchString));
            }

            var groupedStudents = await students.OrderBy(s => s.Class).ToListAsync();
            return View(groupedStudents);
        }

        public async Task<IActionResult> SelectStudent()
        {
            var students = await _context.Students.ToListAsync();
            return View(students);
        }

        public async Task<IActionResult> StudentDetails(int studentId)
        {
            var student = await _context.Students.FindAsync(studentId);

            if (student == null)
            {
                return NotFound();
            }

            var subjects = await _context.Subjects
                .Where(s => s.Class == student.Class)
                .Include(s => s.TeacherSubjects)
                    .ThenInclude(ts => ts.Teachers)
                .Include(s => s.SubjectLanguages)
                .ToListAsync();

            var model = new StudentSubjectsViewModel
            {
                Student = student,
                Subjects = subjects
            };

            return View(model);
        }
    }
}

Controllers/SubjectController.cs
using DataAccessLayer.Entities;
using DataAccessLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CipherStudioTest.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubjectController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Create()
        {
            ViewBag.LanguageList = new List<string> { "English", "French", "Spanish", "German" };
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Subject subject, string[] selectedLanguages)
        {
            try
            {
                if (selectedLanguages.Length == 0)
                {
                    ModelState.AddModelError("Language", "Please select at least one language.");
                    ViewBag.LanguageList = new List<string> { "English", "French", "Spanish", "German" };
                    return View(subject);
                }

                if (ModelState.IsValid)
                {
                    subject.SubjectLanguages = selectedLanguages.Select(lang => new SubjectLanguage { Language = lang }).ToList();
                    _context.Add(subject);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Subject data has been saved successfully!";

                    return RedirectToAction("Create", "Subject");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
            }
            return View(subject);
        }

        public IActionResult AssignTeacher()
        {
            ViewBag.Teachers = new SelectList(_context.Teachers, "Id", "Name");
            ViewBag.Subjects = new SelectList(_context.Subjects.Include(s => s.SubjectLanguages), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignTeacher(int teacherId, int subjectId, string className)
        {
            try
            {
                var exists = _context.TeacherSubjects
                        .Any(ts => ts.TeacherId == teacherId && ts.SubjectId == subjectId && ts.Class == className);

                if (!exists)
                {
                    var teacherSubject = new TeacherSubject
                    {
                        TeacherId = teacherId,
                        SubjectId = subjectId,
                        Class = className
                    };

                    _context.Add(teacherSubject);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Teacher has been assigned successfully!";

                    return RedirectToAction("AssignTeacher", "Subject");
                }
                ModelState.AddModelError("", "This teacher is already assigned to this subject for this class.");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
            }
            return View();
        }

    }
}

Controllers/TeacherController.cs
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Mvc;

namespace CipherStudioTest.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly FileUploadService _fileUploadService;

        public TeacherController(ApplicationDbContext context,FileUploadService fileUploadService)
        {
            _context = context;
            _fileUploadService = fileUploadService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Teacher teacher, IFormFile ImageFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    teacher.ImagePath = await _fileUploadService.UploadFileAsync(ImageFile, "images");
                    _context.Add(teacher);
                    await _context.SaveChangesAsync();
                    TempData["SuccessMessage"] = "Teacher data has been saved successfully!";

                    return RedirectToAction(nameof(Create));
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
            }
            return View(teacher);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CipherStudioTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/students.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CipherStudioTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="List">Student List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Create">Add Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Create">Add Subject</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="AssignTeacher">Assigned Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="SelectStudent">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CipherStudioTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model DataAccessLayer.Entities.Student

<h2>Add Student</h2>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<form asp-action="Create" autocomplete="off" enctype="multipart/form-data" class="form-horizontal">
    <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

    <div class="form-group row">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Age" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Age" class="form-control" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="ImagePath" class="col-sm-2 col-form-label">Image</label>
        <div class="col-sm-10">
            <input type="file" name="ImageFile" class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Class" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Class" class="form-control" />
            <span asp-validation-for="Class" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="RollNumber" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RollNumber" class="form-control" />
            <span asp-validation-for="RollNumber" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000); // 4 seconds delay before auto-dismiss
</script>

Views/Student/List.cshtml
@model IEnumerable<DataAccessLayer.Entities.Student>

<h2>Student List</h2>

<div class="row">
    <div class="col-md-4">
        <form method="get" class="form-inline">
            <div class="input-group">
                <input type="text" name="searchString" class="form-control" placeholder="Search by name" />
                <div class="input-group-append">
                    <button type="submit" class="btn btn-secondary">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div class="col-md-8 text-right">
        <input type="button" value="Add Student Info" class="btn btn-primary"
               onclick="window.location.href='@Url.Action("Create", "Student")'" />
    </div>
</div>


<br />
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Class</th>
            <th>Roll Number</th>
            <th>Age</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
            <tr>
                <td>@student.Name</td>
                <td>@student.Class</td>
                <td>@student.RollNumber</td>
                <td>@student.Age</td>
            </tr>
        }
    </tbody>
</table>

Views/Student/SelectStudent.cshtml
@model IEnumerable<DataAccessLayer.Entities.Student>

<h2>Select a Student</h2>

<form method="get" asp-action="StudentDetails">
    <div class="form-group">
        <label for="studentId">Select Student:</label>
        <select id="studentId" name="studentId" class="form-control">
            <option value="">-- Select Student --</option>
            @foreach (var student in Model)
            {
                <option value="@student.Id">@student.Name</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Get Details</button>
</form>

Views/Student/StudentDetails.cshtml
@model DataAccessLayer.Models.StudentSubjectsViewModel

<h2>Details for @Model.Student.Name</h2>

<p><strong>Class:</strong> @Model.Student.Class</p>

<h3>Subjects</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Subject</th>
            <th>Languages</th>
            <th>Teachers</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var subject in Model.Subjects)
        {
            <tr>
                <td>@subject.Name</td>
                <td>
                    @foreach (var lang in subject.SubjectLanguages)
                    {
                        @lang.Language
                        <br />
                    }
                </td>
                <td>
                    @foreach (var ts in subject.TeacherSubjects)
                    {
                        @ts.Teachers.Name
                        <br />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Subject/AssignTeacher.cshtml
@model DataAccessLayer.Entities.TeacherSubject

<h2>Assign Teacher to Subject</h2>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<form asp-action="AssignTeacher" autocomplete="off" class="form-horizontal">
    <div class="form-group row">
        <label for="TeacherId" class="col-sm-2 col-form-label">Teacher</label>
        <div class="col-sm-10">
            <select asp-for="TeacherId" asp-items="ViewBag.Teachers" class="form-control" required>
                <option value="">--Select Teacher--</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label for="SubjectId" class="col-sm-2 col-form-label">Subject</label>
        <div class="col-sm-10">
            <select asp-for="SubjectId" asp-items="ViewBag.Subjects" class="form-control" required>
                <option value="">--Select Subject--</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Class</label>
        <div class="col-sm-10">
            <input type="text" name="className" class="form-control" />
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Assign</button>
        </div>
    </div>
</form>

<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000); // 4 seconds delay before auto-dismiss
</script>

Views/Subject/Create.cshtml
@model DataAccessLayer.Entities.Subject

<h2>Add Subject</h2>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}


<form asp-action="Create" autocomplete="off" class="form-horizontal">
    <div asp-validation-summary="ModelOnly"></div>

    <div class="form-group row">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Class" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
        <input asp-for="Class" class="form-control" />
            <span asp-validation-for="Class" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Languages</label>
        @foreach (var lang in ViewBag.LanguageList as List<string>)
        {
            <div>
                <input type="checkbox" name="selectedLanguages" value="@lang" /> @lang
            </div>
        }
    </div>

    <div class="form-group row">
        <div class="col-sm-10 offset-sm-2">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000); // 4 seconds delay before auto-dismiss
</script>

Views/Teacher/Create.cshtml
@model DataAccessLayer.Entities.Teacher

<h2>Add Teacher</h2>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<form asp-action="Create" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" />
        <span asp-validation-for="Age"></span>
    </div>

    <div class="form-group">
        <label>Image</label>
        <input type="file" name="ImageFile" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Gender"></label>
        <select asp-for="Gender" class="form-control">
            <option>Male</option>
            <option>Female</option>
            <option>Other</option>
        </select>
        <span asp-validation-for="Gender"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000); // 4 seconds delay before auto-dismiss
</script>